### ISSUE TITLE
Prework- Review my app

### ISSUE THREAD

**Issue by andyblueyo** [andyblueyo/codepath#1]
This is my tipping app; please review /cc @codepathreview

**Comment by chieger** [comment]
Hi Andrea,

Can you please configure your README file using the [README template](http://courses.codepath.com/snippets/intro_to_ios/prework_university.md#heading-4-submit-your-app-for-review-via-github) and add a link to render you animated gif demo of your app?

Also, you will need to [push your entire project to GitHub](https://guides.codepath.com/ios/Using-Git-with-Terminal)

When you have made those changes, please comment to this issue so I can review your submission.

Best,
Charlie Hieger
CodePath University

**Comment by andyblueyo** [comment]
So sorry about that! It should all be good now. I was having problems pushing it to Github, but it's resolved now. 
Thanks, Andrea

**Comment by chieger** [comment]
Hi Andrea, 

Am I looking in the right repository? https://github.com/andyblueyo/codepath

I'm still not seeing any project files or completed README file...

**Comment by andyblueyo** [comment]
Almost. I couldn't push it to master for some reason and so I created a new repository, Tips. 
https://github.com/andyblueyo/codepath/tree/Tips 

Hopefully that should work. Sorry for the delay. 

Thanks, Andrea

**Comment by chieger** [comment]
OK looking good! I think if you remove the `v` from the end of your gif link, it will render correctly within your README file.

This is a great submission Andrea!

In order to even further increase your chances of acceptance and familiarize yourself further with the language, we encourage you take a stab at additional optionals. You can just submit a new Github issue when you’re done and add /cc @codepathreview. No need to refill the pre-work form

This pre-work is a preview of our weekly project process. Generally, weekly projects take about 5 hours to complete the required features and an additional 5 hours to complete the optional features. In general, we've seen that the more hours you log, the quicker you improve your proficiency with iOS.

The purpose of this project was to begin to explore Xcode and to get a broad overview of iOS development using Swift. For example, in this project, we explored the following concepts:

Code styling in Swift. You can find some code styling guides here:

[Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide)
[Github Swift Style Guide](https://github.com/github/swift-style-guide)

- Views are created in Storyboard, Interface Builder, or programmatically, but they have the same goal: instantiate, initialize, and layout view objects. We use IBOutlets to give names to view objects, similar to giving unique ids to divs in HTML.
- We registered for touch events, which can be done programmatically or via IBActions.
- We explored NSUserDefaults, one of the four persistence strategies in iOS.
- View controllers have a set of methods that are called when it loads, appears, or disappears. These are called view controller lifecycle methods.

Do your views look good on iPhone 4, 5, and 6? We will cover in class how to use Auto Layout to robustly design your views for different screen sizes and OS versions.

After this assignment, you should understand the purpose of IBOutlets and IBActions as well as the basics of designing views and programmatically interacting with the views from the controller.

Acceptance emails will be sent out during the first week of January.

Charlie Hieger
CodePath

**Comment by andyblueyo** [comment]
I definitely want to keep improving my app, and I'll see what I can do. Will the classes be online or on person in campus?

Thanks for all your help!

Thanks, Andrea

**Comment by chieger** [comment]
Classes will be held on campus with the rest of the cohort twice a week. There will be homework and online resources also.

Best,
Charlie
